# Generated by Django 5.0 on 2024-02-14 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ViewStockData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sqlModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('trade_code', models.CharField(max_length=25)),
                ('high', models.DecimalField(decimal_places=3, max_digits=10)),
                ('low', models.DecimalField(decimal_places=3, max_digits=10)),
                ('open', models.DecimalField(decimal_places=3, max_digits=10)),
                ('close', models.DecimalField(decimal_places=3, max_digits=10)),
                ('volume', models.IntegerField()),
            ],
        ),
    ]
